### ISSUE TITLE
There doesn't appear to be any testing for this library

### ISSUE THREAD

**Issue by L1lith** [socketkit/socketkit-js#1]
Maybe i missed it but adding a bunch of test cases would be good to make sure everything is operating correctly :)

**Comment by anonrig** [comment]
Thank you for the feedback. We're on the process of converting "Node.js" only SDK to use non-nodejs libraries to add support JavaScript runtimes including but not limited to React Native. We'll be adding new test cases that increase the code coverage to solve this issue.
